### ISSUE TITLE
Black video - only audio.

### ISSUE THREAD

**Issue by wwk-github** [vp-online-courses/asynchronous-javascript-tutorial#4]
https://aviva.udemy.com/course/asynchronous-javascript-promises-callbacks-async-await/learn/lecture/12927040

Please check the video at 4.
It is black-blank.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/50773217/165399796-e2ecf251-01c4-4444-96d7-7539673b912d.png">

**Comment by vp-online-courses** [comment]
Hi wwk-github,

Thanks for letting me know.
I've re-recorded this video and uploaded it again a few months ago.

Have a nice day,
Viktor
